#!/usr/bin/env bash

[ ! -f ./secrets/age-key.txt ] && echo "./secrets/age-key.txt does not exist. aborting installation" && exit 1

mkdir -p "$HOME"/.config/sops/age && cp ./secrets/age-key.txt "$HOME"/.config/sops/age/keys.txt
