#!/bin/sh

MUSIC_DIR=$HOME/music
FORMAT='[[%artist%] - [%title%]#|[%file%]]'
CURRENT="$(mpc current -f "$FORMAT" --wait)"

show_notif() {
  notify-send -i "$2" "Now Playing" "$1"
}

get_albumart() {
  echo $(du -ah "$1" | sort -rh | grep -i -w '\(cover\|folder\)\.\(jpg\|png\)' | head -n 1 | cut -f2-)
}

main() {
  title=$(echo $CURRENT | cut -d '|' -f 1)
  file=$(echo $CURRENT | cut -d '|' -f 2)
  art_dir=$MUSIC_DIR/${file%/*}
  art=$(get_albumart "$art_dir")
  show_notif "$title" "$art"
}

main
