#!/usr/bin/env bash

sleep 1s

. "$HOME/.cache/wal/env-color"

# config file with color values substituted
# with value from env.
CONFIG="$HOME/.config/yambar/config.yml"

echo "$(envsubst < "$CONFIG")" > /tmp/yambar_config.yml
yambar --config /tmp/yambar_config.yml
