#!/usr/bin/env bash

locksway() {
  BACKGROUND="$(mktemp --suffix=.jpg)"

  grim - | magick - \
    -filter Gaussian \
    -resize 20% \
    -define "filter:sigma=1.5" \
    -resize 500% \
    -fill black \
    -colorize 40% \
    "$BACKGROUND"

  swaylock --font monospace --daemonize --image "$BACKGROUND" --scaling fill
}

lockhypr() {
  hyprlock
}

case "$XDG_CURRENT_DESKTOP" in
  *Hyprland*)
    lockhypr
    ;;
  *)
    locksway
    ;;
esac
