#!/usr/bin/env bash

case "$XDG_CURRENT_DESKTOP" in
  *Hyprland*)
    hyprctl dispatch dpms toggle
    ;;
  *)
    for output in $(wlr-randr | grep -e '^[^[:space:]]\+' | cut -d ' ' -f 1); do 
      wlr-randr --output "$output" --toggle
    done
    ;;
esac
